name: amirarabpour
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/lang/
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.otf
          weight: 400
        - asset: assets/fonts/Helvetica-Medium.ttf
          weight: 500
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 700

